name: Check Webhook Dispatch

on:
  repository_dispatch:
    types: [repo-push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          repository: kerzendorf-group/group-data
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true
          token: ${{ secrets.ACCESS_DATA }}

      - name: Check changes
        run: echo "Checking changes made to repository files" 
